#!/usr/bin/env bash
# pdf-studio-api — one-shot homelab setup + build + start. Idempotent.
# Generates a fresh /etc/pdf-studio/prod.env on first run: random MySQL root
# and app-user passwords, DB_URL pointing at the compose sibling. Auth vars
# are left to their in-jar defaults (see application.properties) until you
# provide real values.
set -euo pipefail
here=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
root=$(cd "$here/.." && pwd)

SITE=pdf-studio-api.laxmi.solutions
LEGACY_SITE=pdf-craft.laxmi.solutions
ENV_DST=/etc/pdf-studio/prod.env
DATA=/var/lib/pdf-studio/mysql
CADDYFILE=/etc/caddy/Caddyfile
CADDY_IMPORT=/etc/caddy/pdf-studio.caddy
UNIT=/etc/systemd/system/pdf-studio.service
DB=pdfstudio_db
DB_USER=pdfstudio

log() { printf '\033[1;36m[pdf-studio]\033[0m %s\n' "$*"; }
die() { printf '\033[1;31m[pdf-studio]\033[0m %s\n' "$*" >&2; exit 1; }

[[ $EUID -eq 0 ]] || die "run as root (sudo -E $0)"
command -v docker >/dev/null || die "docker missing"
command -v caddy  >/dev/null || die "caddy missing"

# ── prod.env: generate random secrets on first run; preserve on re-runs so
#    the running DB doesn't lock itself out.
install -d -m 0750 /etc/pdf-studio
if [[ ! -f "$ENV_DST" ]]; then
    root_pw=$(openssl rand -base64 24 | tr -d '/+=' | head -c 32)
    app_pw=$(openssl rand -base64 24 | tr -d '/+=' | head -c 32)
    install -m 0600 /dev/null "$ENV_DST"
    cat >> "$ENV_DST" <<EOF
# Generated by deploy/deploy.sh — edit auth/mail/billing vars as needed.
# MySQL container init (mysql:9 image reads these on first boot).
MYSQL_ROOT_PASSWORD=$root_pw
MYSQL_DATABASE=$DB
MYSQL_USER=$DB_USER
MYSQL_PASSWORD=$app_pw
# Spring datasource — DB_URL is a full JDBC URL (see application-prod.properties).
DB_URL=jdbc:mysql://pdf-studio-mysql:3306/$DB?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
DB_USERNAME=$DB_USER
DB_PASSWORD=$app_pw
DB_POOL_MAX=10
DB_POOL_MIN=2
EOF
    log "wrote fresh $ENV_DST with generated MYSQL_ROOT_PASSWORD + app credentials"
else
    log "$ENV_DST already exists — keeping it"
fi

# ── data dir (mysql UID 999 in the official image).
install -d -m 0700 -o 999 -g 999 "$DATA"

# ── systemd unit.
install -m 0644 "$here/pdf-studio.service" "$UNIT"
systemctl daemon-reload
systemctl enable pdf-studio.service >/dev/null 2>&1 || true

# ── caddy: publish the shared snippet, then wire both site blocks. Repoints
#    the legacy pdf-craft.laxmi.solutions block (bare `reverse_proxy
#    localhost:8082`) to `import` the same snippet so both hostnames route
#    to the same backend and any future tweak is one edit.
install -m 0644 "$here/pdf-studio.caddy" "$CADDY_IMPORT"

repoint_legacy() {
    # Rewrite `<legacy> { … }` to `<legacy> { import <snippet> }` iff the
    # existing body isn't already the import. Uses the same awk pattern
    # deploy/scripts/install-caddy.sh (ls-judge) uses for runtimes.*.
    local tmp
    tmp=$(mktemp)
    awk -v site="$LEGACY_SITE" -v imp="$CADDY_IMPORT" '
        BEGIN { d=0; b=0; done=0 }
        !b && d==0 && $1==site && $NF=="{" {
            b=1; d=1
            print site " {"
            print "\timport " imp
            print "}"
            done=1
            next
        }
        b {
            for (i=1; i<=length($0); i++) {
                c=substr($0,i,1)
                if (c=="{") d++
                else if (c=="}") d--
            }
            if (d==0) b=0
            next
        }
        { print }
    ' "$CADDYFILE" > "$tmp"
    if ! cmp -s "$tmp" "$CADDYFILE"; then
        cp -a "$CADDYFILE" "$CADDYFILE.bak.$(date -u +%Y%m%d-%H%M%SZ)"
        mv "$tmp" "$CADDYFILE"
        log "repointed legacy $LEGACY_SITE to import $CADDY_IMPORT"
    else
        rm -f "$tmp"
    fi
}
repoint_legacy

if ! grep -qE "^${SITE//./\\.}[[:space:]]*\{" "$CADDYFILE"; then
    printf '\n%s {\n\timport %s\n}\n' "$SITE" "$CADDY_IMPORT" >> "$CADDYFILE"
    log "appended site block for $SITE"
fi
caddy validate --config "$CADDYFILE" --adapter caddyfile >/dev/null
systemctl reload caddy
log "caddy reloaded"

# ── build image if missing (first-time build downloads Maven deps).
if ! docker image inspect pdf-studio-api:homelab >/dev/null 2>&1; then
    log "building pdf-studio-api:homelab (first-time build)"
    (cd "$root" && docker compose -f docker-compose.homelab.yml build)
fi

log "starting pdf-studio.service"
systemctl restart pdf-studio.service
systemctl --no-pager status pdf-studio.service | head -8 || true
log "done — https://$SITE (via pdf-craft.laxmi.solutions today, until DNS flips)"
